FROM locustio/locust:2.20.0

# Copiar scripts de pruebas
COPY ./scripts/ /scripts/
WORKDIR /scripts

# Instalar dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt

# Configurar entorno
ENV LOCUST_LOCUSTFILE load_tests.py
ENV PYTHONPATH .