services:
  skafs-cloud:
    build:
      context: ./IoT
      dockerfile: ./cloud/SKAFS/Dockerfile
    container_name: skafs-cloud
    networks:
      - skafs_network
    volumes:
      - ./Logs:/logs
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    ports:
      - 8011:8011 #Prometheus
      - 5001:5001 #Socket Device
    command: [ "python", "-m", "cloud.skafs_cloud" ]

  skafs-gateway:
    build:
      context: ./IoT
      dockerfile: ./gateway/SKAFS/Dockerfile
    container_name: skafs-gateway
    depends_on:
      - skafs-cloud
    networks:
      - skafs_network
    volumes:
      - ./Logs:/logs
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    ports:
      - 8010:8010 #Prometheus
      - 5000:5000 #Socket
      - 6000:6000 #Socket revocation
    command: [ "python", "-m", "gateway.skafs_gateway" ]

  skafs-device:
    build:
      context: ./IoT
      dockerfile: ./device/SKAFS/Dockerfile
    depends_on:
      - skafs-gateway
    networks:
      - skafs_network
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    volumes:
      - ./Logs:/logs
    ports:
      - 8012:8012 #Prometheus
    command: [ "python", "-m", "device.skafs_device" ]

  sniffer-capture:
    build:
      context: ./Sniffing
      dockerfile: Dockerfile.capture
    network_mode: host # Capturar tráfico del host
    volumes:
      - ./Sniffing/shared_data:/shared_data  # Volumen compartido
      - ./Logs:/logs
    cap_add:
      - NET_ADMIN # Permiso para sniffing
    command: [ "python", "-m", "capture_script" ]
    restart: on-failure

  sniffer-replicate:
    build:
      context: ./Sniffing
      dockerfile: Dockerfile.replicate
    networks:
      - skafs_network
    volumes:
      - ./Sniffing/shared_data:/shared_data  # Mismo volumen compartido
      - ./Logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["python", "-m", "replicate_script"]
    restart: on-failure

networks:
  skafs_network:
    driver: bridge

volumes:
  shared_data:  # Volumen compartido entre ambos sniffers
    driver: local